# Author: Aaron Yerke (aaronyerke@gmail.com)
configfile: "workflow/config/config.yaml"

from snakemake.utils import min_version
min_version("8.9.0")

# List constants to use as wildcards
response_cols = ["mpg","good_milage","car_name"]

rule all:
	input:"output/unit_test/tables/rf_test_scores.csv"

rule create_test_rf_dataset:
	conda:"/project/scinet_workshop1/snakemake/snakemake_env" #Note, this is a prebuilt environment for the SCINet tutorial, for running outside of the tutorial, comment/delete this line and and uncomment the following line.
	# conda:"env/snk_mk_conda_env.yml",
	output:
		"data/unit_test/mtc_predictor.csv",
		"data/unit_test/mtc_response.csv"
	shell:
		"""
		Rscript workflow/scripts/data_org/make_rf_test_dfs.R
		"""

rule aggregate_rf_tables_test_data:
	conda:"/project/scinet_workshop1/snakemake/snakemake_env" #Note, this is a prebuilt environment for the SCINet tutorial, for running outside of the tutorial, comment/delete this line and and uncomment the following line.
	# conda:"env/snk_mk_conda_env.yml",
	input:expand("output/unit_test/tables/1col{respns_column}?rf_test_scores.csv", respns_column=response_cols)
	output: "output/unit_test/tables/rf_test_scores.csv"
	shell:
		"""
		echo "{input}"
		Rscript workflow/scripts/data_org/combine_rf_data.R --out_subdir unit_test --fn_root rf_test
		"""

rule rf_test_dataset:
	conda:"/project/scinet_workshop1/snakemake/snakemake_env" #Note, this is a prebuilt environment for the SCINet tutorial, for running outside of the tutorial, comment/delete this line and and uncomment the following line.
	# conda:"env/snk_mk_conda_env.yml",
	input:
		pred = "data/unit_test/mtc_predictor.csv",
		resp = "data/unit_test/mtc_response.csv"
	output:
		"output/unit_test/tables/1col{respns_column}?rf_test_scores.csv"
	resources:
		runtime=10, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem_mb="8gb"
	shell:
		"""
		python workflow/scripts/ml/random_forest.py \
				--response_fn {input.resp} \
				--delimeter , \
				--pred_path {input.pred} \
				--out_folder unit_test \
				--output_label rf_test \
				--title rf_test \
				--response_col {wildcards.respns_column:q}
		"""
