#This was a big help: https://github.com/jdblischak/smk-simple-slurm/blob/main/simple/config.v8%2B.yaml#L5
executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p slurmLogs/{rule:q} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-'{wildcards:q}'
    --output=slurmLogs/{rule}/'{wildcards:q}'-%x.%j.log
    --error=slurmLogs/{rule}/'{wildcards:q}'-%x.%j.log
    --mail-type=BEGIN,END,FAIL
    --parsable
    # --mail-user=scinet.fellow@usda.gov #update your own email here.
default-resources:
  - partition=ceres
  - mem_mb=1000
  - time=120 #num minutes
  - nodes=1
  - ntasks=1
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 120
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: TRUE

